// ── Re-export all types ──────────────────────────────────────────────
export type {
	CurrentUser,
	CollectionListItem,
	CollectionItem,
	DashboardListItem,
	DashboardDetail,
	PublicCardDetail,
	PublicDashboardDetail,
	DashboardCard,
	CardListItem,
	CardDetail,
	AnalysisDraftListItem,
	AnalysisDraftDetail,
	AnalysisDraftRunResponse,
	AnalysisDraftSaveCardResponse,
	CardQueryResponse,
	DashboardQueryResponse,
	Nl2SqlEvalCaseItem,
	Nl2SqlEvalRunRow,
	Nl2SqlEvalRunSummary,
	AiAgentToolCallRecord,
	MicroFormRiskLevel,
	MicroFormFieldSchema,
	MicroFormSchema,
	AiAgentPendingAction,
	AiAgentChatResponse,
	AiAgentChatSession,
	AiAgentChatMessage,
	AiAgentChatSessionDetail,
	CopilotSuggestedQuestion,
	Nl2SqlEvalRunRecord,
	Nl2SqlEvalGateRunResponse,
	Nl2SqlEvalCompareResponse,
	ExplainabilityResponse,
	ExploreSessionItem,
	ReportTemplateItem,
	FixedReportCatalogItem,
	FixedReportRunResponse,
	ReportRunItem,
	MetricLensSummary,
	MetricLensDetail,
	MetricLensCompare,
	QueryTraceFailureSummary,
	SearchItem,
	SearchResponse,
	TrashItem,
	TrashResponse,
	DatabaseListItem,
	DatabaseListResponse,
	DatabaseMetadataResponse,
	DatasetCacheStats,
	DatasetCachePolicy,
	DatabaseValidateResponse,
	DatabaseCreateResponse,
	ManagedDataSourceCreatePayload,
	PlatformDataSourceItem,
	TableSummary,
	TableDetail,
	FieldDetail,
	FieldValuesResponse,
	Metric,
	PlatformMetric,
	VisibleTable,
	PublicScreenDetail,
	CopilotSiteSettings,
	CopilotProviderTemplate,
	CopilotProvider,
	CopilotProviderPayload,
	CopilotProviderTestResult,
	CopilotApiKeyItem,
	CopilotApiKeyReveal,
	CopilotApiKeyCreatePayload,
	ScreenListItem,
	ScreenDetail,
	ScreenWarmupSummary,
	ScreenAiGenerationRequest,
	ScreenAiRevisionRequest,
	ScreenAiGenerationResponse,
	ScreenSpecValidationResponse,
	ScreenTemplateItem,
	ScreenTemplateVersionItem,
	ScreenPluginComponent,
	ScreenPluginDataSource,
	ScreenPluginManifest,
	ScreenPluginValidationResult,
	ScreenIndustryPack,
	ScreenIndustryPackImportResult,
	ScreenIndustryPackPresets,
	ScreenIndustryPackValidationResult,
	ScreenIndustryPackAuditRow,
	ScreenIndustryConnectorPlan,
	ScreenIndustryConnectorProbe,
	ScreenIndustryOpsHealth,
	ScreenIndustryRuntimeProbe,
	ScreenIndustryOpsHealthSummary,
	ScreenIndustryOpsHealthCheck,
	ScreenIndustryRuntimeProbeSummary,
	ScreenIndustryRuntimeProbeRow,
	ScreenCompliancePolicy,
	ScreenComplianceReport,
	ScreenComplianceReportQuery,
	ScreenVersion,
	ScreenVersionDiff,
	ScreenAclEntry,
	ScreenAuditEntry,
	ScreenComment,
	ScreenCommentChanges,
	ScreenCollaborationPresenceRow,
	ScreenCollaborationPresence,
	ScreenEditLock,
	ScreenPublicLinkPolicy,
	ScreenHealthStats,
	ScreenHealthReport,
	ScreenExportPrepareRequest,
	ScreenExportPrepareResult,
	ScreenExportReportRequest,
	ScreenExportReportResult,
	ScreenExportRenderRequest,
	ScreenExportRenderResult,
	ScreenComponentData,
	CopilotStreamEvent,
} from "./types.ts";

// ── Re-export HTTP utilities ─────────────────────────────────────────
export { HttpError, AuthError, isRetryableHttpError } from "./httpClient.ts";

// ── Re-export SSE streaming function ─────────────────────────────────
export { aiAgentChatSendStream } from "./modules/copilot.ts";

// ── Compose the analyticsApi object from sub-modules ─────────────────
import { authApi } from "./modules/auth.ts";
import { databaseApi } from "./modules/database.ts";
import { cardApi } from "./modules/card.ts";
import { dashboardApi } from "./modules/dashboard.ts";
import { screenApi } from "./modules/screen.ts";
import { copilotApi } from "./modules/copilot.ts";
import { adminApi } from "./modules/admin.ts";

export const analyticsApi = {
	...authApi,
	...databaseApi,
	...cardApi,
	...dashboardApi,
	...screenApi,
	...copilotApi,
	...adminApi,
};
